sudo: required
services:
  - docker

before_install:
  - docker build -t zavanton/django-api-test -f ./app/Dockerfile ./app

script:
  - docker run -e CI=true -e DEBUG=1 -e SECRET_KEY=foo -e DJANGO_ALLOWED_HOSTS='localhost 127.0.0.1 [::1]' -e SQL_ENGINE=django.db.backends.postgresql -e SQL_DATABASE=hello_django_dev -e SQL_USER=hello_django -e SQL_PASSWORD=hello_django -e SQL_HOST=db -e SQL_PORT=5432 -e DATABASE=postgres zavanton/django-api-test python manage.py test

after_success:
  # build docker images
  - docker build -t zavanton/django-api -f ./app/Dockerfile.prod ./app
  - docker build -t zavanton/django-nginx -f ./nginx/Dockerfile ./nginx
  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to Docker Hub
  - docker push zavanton/django-api
  - docker push zavanton/django-nginx

#deploy:
#  provider: elasticbeanstalk
#  region: us-east-2
#  app: multi-docker
#  env: Multidocker-env
#  bucket_name: elasticbeanstalk-us-east-2-565447122202
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#